<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Models\GetBalanceOperationResponse;
use PagarmeApiSDKLib\Models\ListBalanceOperationResponse;
use PagarmeApiSDKLib\Mock\MockIdGenerator;
use PagarmeApiSDKLib\Mock\MockDataProvider;

class BalanceOperationsController extends BaseController
{
    /**
     * @param int $id
     *
     * @return GetBalanceOperationResponse Response from the API call
     */
    public function getBalanceOperationById(int $id): GetBalanceOperationResponse
    {
        return $this->buildMockBalanceOperation(MockIdGenerator::generate('bo'));
    }

    /**
     * @param string|null $status
     * @param \DateTime|null $createdSince
     * @param \DateTime|null $createdUntil
     * @param string|null $recipientId
     *
     * @return ListBalanceOperationResponse Response from the API call
     */
    public function getBalanceOperations(
        ?string $status = null,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null,
        ?string $recipientId = null
    ): ListBalanceOperationResponse {
        $operation = $this->buildMockBalanceOperation(MockIdGenerator::generate('bo'));
        $paging = MockDataProvider::paging(1);

        $response = new ListBalanceOperationResponse();
        $response->setData([$operation]);
        $response->setPaging($paging);
        return $response;
    }

    private function buildMockBalanceOperation(string $id): GetBalanceOperationResponse
    {
        $response = new GetBalanceOperationResponse();
        $response->setId($id);
        $response->setStatus('available');
        $response->setBalanceAmount('100000');
        $response->setBalanceOldAmount('90000');
        $response->setType('credit');
        $response->setAmount(10000);
        $response->setFee('0');
        $response->setCreatedAt((new \DateTime())->format('c'));
        return $response;
    }
}
