<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Exceptions\ApiException;
use PagarmeApiSDKLib\Models\CreateCancelChargeRequest;
use PagarmeApiSDKLib\Models\CreateCaptureChargeRequest;
use PagarmeApiSDKLib\Models\CreateChargeRequest;
use PagarmeApiSDKLib\Models\CreateConfirmPaymentRequest;
use PagarmeApiSDKLib\Models\GetChargeResponse;
use PagarmeApiSDKLib\Models\GetChargesSummaryResponse;
use PagarmeApiSDKLib\Models\ListChargesResponse;
use PagarmeApiSDKLib\Models\ListChargeTransactionsResponse;
use PagarmeApiSDKLib\Models\UpdateChargeCardRequest;
use PagarmeApiSDKLib\Models\UpdateChargeDueDateRequest;
use PagarmeApiSDKLib\Models\UpdateChargePaymentMethodRequest;
use PagarmeApiSDKLib\Models\UpdateMetadataRequest;
use PagarmeApiSDKLib\Mock\MockDataProvider;
use PagarmeApiSDKLib\Mock\MockWebhookDispatcher;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class ChargesController extends BaseController
{
    /**
     * Updates the metadata from a charge
     *
     * @param string $chargeId The charge id
     * @param UpdateMetadataRequest $request Request for updating the charge metadata
     * @param string|null $idempotencyKey
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateChargeMetadata(
        string $chargeId,
        UpdateMetadataRequest $request,
        ?string $idempotencyKey = null
    ): GetChargeResponse {
        $charge = MockDataProvider::charge();
        $charge->setId($chargeId);
        $charge->setMetadata($request->getMetadata());
        return $charge;
    }

    /**
     * Captures a charge
     *
     * @param string $chargeId Charge id
     * @param CreateCaptureChargeRequest|null $request Request for capturing a charge
     * @param string|null $idempotencyKey
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function captureCharge(
        string $chargeId,
        ?CreateCaptureChargeRequest $request = null,
        ?string $idempotencyKey = null
    ): GetChargeResponse {
        $amount = $request ? $request->getAmount() : 10000;
        $charge = MockDataProvider::charge($amount, 'paid');
        $charge->setId($chargeId);
        return $charge;
    }

    /**
     * Get a charge from its id
     *
     * @param string $chargeId Charge id
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getCharge(string $chargeId): GetChargeResponse
    {
        $charge = MockDataProvider::charge();
        $charge->setId($chargeId);
        return $charge;
    }

    /**
     * @param string $chargeId
     * @param CreateConfirmPaymentRequest|null $request Request for confirm payment
     * @param string|null $idempotencyKey
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function confirmPayment(
        string $chargeId,
        ?CreateConfirmPaymentRequest $request = null,
        ?string $idempotencyKey = null
    ): GetChargeResponse {
        $charge = MockDataProvider::charge(10000, 'paid');
        $charge->setId($chargeId);
        return $charge;
    }

    /**
     * @param string $chargeId Charge Id
     * @param int|null $page Page number
     * @param int|null $size Page size
     *
     * @return ListChargeTransactionsResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getChargeTransactions(
        string $chargeId,
        ?int $page = null,
        ?int $size = null
    ): ListChargeTransactionsResponse {
        $tx1 = MockDataProvider::creditCardTransaction(10000);
        $tx2 = MockDataProvider::creditCardTransaction(5000);
        return MockDataProvider::listChargeTransactions([$tx1, $tx2], 2);
    }

    /**
     * Updates the card from a charge
     *
     * @param string $chargeId Charge id
     * @param UpdateChargeCardRequest $request Request for updating a charge's card
     * @param string|null $idempotencyKey
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateChargeCard(
        string $chargeId,
        UpdateChargeCardRequest $request,
        ?string $idempotencyKey = null
    ): GetChargeResponse {
        $charge = MockDataProvider::charge();
        $charge->setId($chargeId);
        return $charge;
    }

    /**
     * Creates a new charge
     *
     * @param CreateChargeRequest $request Request for creating a charge
     * @param string|null $idempotencyKey
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createCharge(CreateChargeRequest $request, ?string $idempotencyKey = null): GetChargeResponse
    {
        $amount = $request->getAmount() ?? 10000;
        $paymentMethod = $request->getPaymentMethod() ?? 'credit_card';
        $customer = null;
        $metadata = $request->getMetadata() ?? [];
        $code = $request->getCode() ?? null;

        $charge = MockDataProvider::charge(
            $amount,
            'paid',
            $paymentMethod,
            $code,
            $customer,
            $metadata
        );

        MockWebhookDispatcher::dispatchChargePaid([
            'id' => $charge->getId(),
            'code' => $charge->getCode(),
            'amount' => $charge->getAmount(),
            'status' => $charge->getStatus(),
            'payment_method' => $charge->getPaymentMethod(),
        ]);

        return $charge;
    }

    /**
     * Updates a charge's payment method
     *
     * @param string $chargeId Charge id
     * @param UpdateChargePaymentMethodRequest $request Request for updating the payment method from
     *        a charge
     * @param string|null $idempotencyKey
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateChargePaymentMethod(
        string $chargeId,
        UpdateChargePaymentMethodRequest $request,
        ?string $idempotencyKey = null
    ): GetChargeResponse {
        $paymentMethod = $request->getPaymentMethod() ?? 'credit_card';
        $charge = MockDataProvider::charge(10000, null, $paymentMethod);
        $charge->setId($chargeId);
        return $charge;
    }

    /**
     * Updates the due date from a charge
     *
     * @param string $chargeId Charge Id
     * @param UpdateChargeDueDateRequest $request Request for updating the due date
     * @param string|null $idempotencyKey
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateChargeDueDate(
        string $chargeId,
        UpdateChargeDueDateRequest $request,
        ?string $idempotencyKey = null
    ): GetChargeResponse {
        $charge = MockDataProvider::charge();
        $charge->setId($chargeId);
        return $charge;
    }

    /**
     * @param string $status
     * @param \DateTime|null $createdSince
     * @param \DateTime|null $createdUntil
     *
     * @return GetChargesSummaryResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getChargesSummary(
        string $status,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null
    ): GetChargesSummaryResponse {
        $summary = new GetChargesSummaryResponse();
        $summary->setTotal(150);
        return $summary;
    }

    /**
     * Retries a charge
     *
     * @param string $chargeId Charge id
     * @param string|null $idempotencyKey
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function retryCharge(string $chargeId, ?string $idempotencyKey = null): GetChargeResponse
    {
        $charge = MockDataProvider::charge(10000, 'pending');
        $charge->setId($chargeId);
        return $charge;
    }

    /**
     * Lists all charges
     *
     * @param int|null $page Page number
     * @param int|null $size Page size
     * @param string|null $code Filter for charge's code
     * @param string|null $status Filter for charge's status
     * @param string|null $paymentMethod Filter for charge's payment method
     * @param string|null $customerId Filter for charge's customer id
     * @param string|null $orderId Filter for charge's order id
     * @param \DateTime|null $createdSince Filter for the beginning of the range for charge's
     *        creation
     * @param \DateTime|null $createdUntil Filter for the end of the range for charge's creation
     *
     * @return ListChargesResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getCharges(
        ?int $page = null,
        ?int $size = null,
        ?string $code = null,
        ?string $status = null,
        ?string $paymentMethod = null,
        ?string $customerId = null,
        ?string $orderId = null,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null
    ): ListChargesResponse {
        $charge1 = MockDataProvider::charge(10000, $status ?? 'paid', $paymentMethod ?? 'credit_card');
        $charge2 = MockDataProvider::charge(25000, $status ?? 'paid', $paymentMethod ?? 'credit_card');
        return MockDataProvider::listCharges([$charge1, $charge2], 2);
    }

    /**
     * Cancel a charge
     *
     * @param string $chargeId Charge id
     * @param CreateCancelChargeRequest|null $request Request for cancelling a charge
     * @param string|null $idempotencyKey
     *
     * @return GetChargeResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cancelCharge(
        string $chargeId,
        ?CreateCancelChargeRequest $request = null,
        ?string $idempotencyKey = null
    ): GetChargeResponse {
        $charge = MockDataProvider::charge(10000, 'canceled');
        $charge->setId($chargeId);
        return $charge;
    }
}
