<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Models\CreateAccessTokenRequest;
use PagarmeApiSDKLib\Models\CreateAddressRequest;
use PagarmeApiSDKLib\Models\CreateCardRequest;
use PagarmeApiSDKLib\Models\CreateCustomerRequest;
use PagarmeApiSDKLib\Models\GetAccessTokenResponse;
use PagarmeApiSDKLib\Models\GetAddressResponse;
use PagarmeApiSDKLib\Models\GetCardResponse;
use PagarmeApiSDKLib\Models\GetCustomerResponse;
use PagarmeApiSDKLib\Models\ListAccessTokensResponse;
use PagarmeApiSDKLib\Models\ListAddressesResponse;
use PagarmeApiSDKLib\Models\ListCardsResponse;
use PagarmeApiSDKLib\Models\ListCustomersResponse;
use PagarmeApiSDKLib\Models\UpdateAddressRequest;
use PagarmeApiSDKLib\Models\UpdateCardRequest;
use PagarmeApiSDKLib\Models\UpdateCustomerRequest;
use PagarmeApiSDKLib\Models\UpdateMetadataRequest;
use PagarmeApiSDKLib\Mock\MockDataProvider;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class CustomersController extends BaseController
{
    /**
     * Creates a new address for a customer
     *
     * @param string $customerId Customer Id
     * @param CreateAddressRequest $request Request for creating an address
     * @param string|null $idempotencyKey
     *
     * @return GetAddressResponse Response from the API call
     */
    public function createAddress(
        string $customerId,
        CreateAddressRequest $request,
        ?string $idempotencyKey = null
    ): GetAddressResponse {
        return MockDataProvider::address($customerId);
    }

    /**
     * Updates a card
     *
     * @param string $customerId Customer Id
     * @param string $cardId Card id
     * @param UpdateCardRequest $request Request for updating a card
     * @param string|null $idempotencyKey
     *
     * @return GetCardResponse Response from the API call
     */
    public function updateCard(
        string $customerId,
        string $cardId,
        UpdateCardRequest $request,
        ?string $idempotencyKey = null
    ): GetCardResponse {
        $card = MockDataProvider::card();
        $card->setId($cardId);
        return $card;
    }

    /**
     * Delete a customer's access token
     *
     * @param string $customerId Customer Id
     * @param string $tokenId Token Id
     * @param string|null $idempotencyKey
     *
     * @return GetAccessTokenResponse Response from the API call
     */
    public function deleteAccessToken(
        string $customerId,
        string $tokenId,
        ?string $idempotencyKey = null
    ): GetAccessTokenResponse {
        $token = new GetAccessTokenResponse();
        $token->setId($tokenId);
        $token->setCode('mock_token_code');
        $token->setStatus('deleted');
        $token->setCreatedAt(new \DateTime());
        return $token;
    }

    /**
     * Creates a new customer
     *
     * @param CreateCustomerRequest $request Request for creating a customer
     * @param string|null $idempotencyKey
     *
     * @return GetCustomerResponse Response from the API call
     */
    public function createCustomer(CreateCustomerRequest $request, ?string $idempotencyKey = null): GetCustomerResponse
    {
        return MockDataProvider::customer(
            $request->getName(),
            $request->getEmail(),
            $request->getDocument(),
            $request->getCode(),
            $request->getType()
        );
    }

    /**
     * Delete a Customer's access tokens
     *
     * @param string $customerId Customer Id
     *
     * @return ListAccessTokensResponse Response from the API call
     */
    public function deleteAccessTokens(string $customerId): ListAccessTokensResponse
    {
        $token = new GetAccessTokenResponse();
        $token->setId(MockIdGenerator::generate('token'));
        $token->setCode('mock_token_code');
        $token->setStatus('deleted');
        $token->setCreatedAt(new \DateTime());

        $list = new ListAccessTokensResponse();
        $list->setData([$token]);
        $list->setPaging(MockDataProvider::paging(1));
        return $list;
    }

    /**
     * Updates an address
     *
     * @param string $customerId Customer Id
     * @param string $addressId Address Id
     * @param UpdateAddressRequest $request Request for updating an address
     * @param string|null $idempotencyKey
     *
     * @return GetAddressResponse Response from the API call
     */
    public function updateAddress(
        string $customerId,
        string $addressId,
        UpdateAddressRequest $request,
        ?string $idempotencyKey = null
    ): GetAddressResponse {
        $addr = MockDataProvider::address($customerId);
        $addr->setId($addressId);
        return $addr;
    }

    /**
     * Get a customer's address
     *
     * @param string $customerId Customer id
     * @param string $addressId Address Id
     *
     * @return GetAddressResponse Response from the API call
     */
    public function getAddress(string $customerId, string $addressId): GetAddressResponse
    {
        $addr = MockDataProvider::address($customerId);
        $addr->setId($addressId);
        return $addr;
    }

    /**
     * Delete a Customer's address
     *
     * @param string $customerId Customer Id
     * @param string $addressId Address Id
     * @param string|null $idempotencyKey
     *
     * @return GetAddressResponse Response from the API call
     */
    public function deleteAddress(
        string $customerId,
        string $addressId,
        ?string $idempotencyKey = null
    ): GetAddressResponse {
        $addr = MockDataProvider::address($customerId);
        $addr->setId($addressId);
        $addr->setStatus('deleted');
        return $addr;
    }

    /**
     * Get all Customers
     *
     * @param string|null $name Name of the Customer
     * @param string|null $document Document of the Customer
     * @param int|null $page Current page the the search
     * @param int|null $size Quantity pages of the search
     * @param string|null $email Customer's email
     * @param string|null $code Customer's code
     *
     * @return ListCustomersResponse Response from the API call
     */
    public function getCustomers(
        ?string $name = null,
        ?string $document = null,
        ?int $page = 1,
        ?int $size = 10,
        ?string $email = null,
        ?string $code = null
    ): ListCustomersResponse {
        return MockDataProvider::listCustomers([
            MockDataProvider::customer('Mock Customer 1'),
            MockDataProvider::customer('Mock Customer 2'),
        ], 2);
    }

    /**
     * Get all access tokens from a customer
     *
     * @param string $customerId Customer Id
     * @param int|null $page Page number
     * @param int|null $size Page size
     *
     * @return ListAccessTokensResponse Response from the API call
     */
    public function getAccessTokens(string $customerId, ?int $page = null, ?int $size = null): ListAccessTokensResponse
    {
        $token = new GetAccessTokenResponse();
        $token->setId(MockIdGenerator::generate('token'));
        $token->setCode('mock_token_code');
        $token->setStatus('active');
        $token->setCreatedAt(new \DateTime());

        $list = new ListAccessTokensResponse();
        $list->setData([$token]);
        $list->setPaging(MockDataProvider::paging(1));
        return $list;
    }

    /**
     * Delete a customer's card
     *
     * @param string $customerId Customer Id
     * @param string $cardId Card Id
     * @param string|null $idempotencyKey
     *
     * @return GetCardResponse Response from the API call
     */
    public function deleteCard(string $customerId, string $cardId, ?string $idempotencyKey = null): GetCardResponse
    {
        $card = MockDataProvider::card();
        $card->setId($cardId);
        $card->setStatus('deleted');
        return $card;
    }

    /**
     * Get a customer's card
     *
     * @param string $customerId Customer id
     * @param string $cardId Card id
     *
     * @return GetCardResponse Response from the API call
     */
    public function getCard(string $customerId, string $cardId): GetCardResponse
    {
        $card = MockDataProvider::card();
        $card->setId($cardId);
        return $card;
    }

    /**
     * Creates a new card for a customer
     *
     * @param string $customerId Customer id
     * @param CreateCardRequest $request Request for creating a card
     * @param string|null $idempotencyKey
     *
     * @return GetCardResponse Response from the API call
     */
    public function createCard(
        string $customerId,
        CreateCardRequest $request,
        ?string $idempotencyKey = null
    ): GetCardResponse {
        $holderName = method_exists($request, 'getHolderName') ? $request->getHolderName() : null;
        $number = method_exists($request, 'getNumber') ? $request->getNumber() : null;
        $expMonth = method_exists($request, 'getExpMonth') ? $request->getExpMonth() : null;
        $expYear = method_exists($request, 'getExpYear') ? $request->getExpYear() : null;

        return MockDataProvider::card($holderName, $number, $expMonth, $expYear);
    }

    /**
     * Get a Customer's access token
     *
     * @param string $customerId Customer Id
     * @param string $tokenId Token Id
     *
     * @return GetAccessTokenResponse Response from the API call
     */
    public function getAccessToken(string $customerId, string $tokenId): GetAccessTokenResponse
    {
        $token = new GetAccessTokenResponse();
        $token->setId($tokenId);
        $token->setCode('mock_token_code');
        $token->setStatus('active');
        $token->setCreatedAt(new \DateTime());
        return $token;
    }

    /**
     * Gets all adressess from a customer
     *
     * @param string $customerId Customer id
     * @param int|null $page Page number
     * @param int|null $size Page size
     *
     * @return ListAddressesResponse Response from the API call
     */
    public function getAddresses(string $customerId, ?int $page = null, ?int $size = null): ListAddressesResponse
    {
        $list = new ListAddressesResponse();
        $list->setData([
            MockDataProvider::address($customerId),
            MockDataProvider::address($customerId),
        ]);
        $list->setPaging(MockDataProvider::paging(2));
        return $list;
    }

    /**
     * Updates a customer
     *
     * @param string $customerId Customer id
     * @param UpdateCustomerRequest $request Request for updating a customer
     * @param string|null $idempotencyKey
     *
     * @return GetCustomerResponse Response from the API call
     */
    public function updateCustomer(
        string $customerId,
        UpdateCustomerRequest $request,
        ?string $idempotencyKey = null
    ): GetCustomerResponse {
        $cus = MockDataProvider::customer();
        $cus->setId($customerId);
        return $cus;
    }

    /**
     * Creates a access token for a customer
     *
     * @param string $customerId Customer Id
     * @param CreateAccessTokenRequest $request Request for creating a access token
     * @param string|null $idempotencyKey
     *
     * @return GetAccessTokenResponse Response from the API call
     */
    public function createAccessToken(
        string $customerId,
        CreateAccessTokenRequest $request,
        ?string $idempotencyKey = null
    ): GetAccessTokenResponse {
        $token = new GetAccessTokenResponse();
        $token->setId(MockIdGenerator::generate('token'));
        $token->setCode('mock_token_code');
        $token->setStatus('active');
        $token->setCreatedAt(new \DateTime());
        return $token;
    }

    /**
     * Get all cards from a customer
     *
     * @param string $customerId Customer Id
     * @param int|null $page Page number
     * @param int|null $size Page size
     *
     * @return ListCardsResponse Response from the API call
     */
    public function getCards(string $customerId, ?int $page = null, ?int $size = null): ListCardsResponse
    {
        return MockDataProvider::listCards([
            MockDataProvider::card(),
            MockDataProvider::card(),
        ], 2);
    }

    /**
     * Renew a card
     *
     * @param string $customerId Customer id
     * @param string $cardId Card Id
     * @param string|null $idempotencyKey
     *
     * @return GetCardResponse Response from the API call
     */
    public function renewCard(string $customerId, string $cardId, ?string $idempotencyKey = null): GetCardResponse
    {
        $card = MockDataProvider::card();
        $card->setId($cardId);
        return $card;
    }

    /**
     * Updates the metadata a customer
     *
     * @param string $customerId The customer id
     * @param UpdateMetadataRequest $request Request for updating the customer metadata
     * @param string|null $idempotencyKey
     *
     * @return GetCustomerResponse Response from the API call
     */
    public function updateCustomerMetadata(
        string $customerId,
        UpdateMetadataRequest $request,
        ?string $idempotencyKey = null
    ): GetCustomerResponse {
        $cus = MockDataProvider::customer();
        $cus->setId($customerId);
        $cus->setMetadata($request->getMetadata());
        return $cus;
    }

    /**
     * Get a customer
     *
     * @param string $customerId Customer Id
     *
     * @return GetCustomerResponse Response from the API call
     */
    public function getCustomer(string $customerId): GetCustomerResponse
    {
        $cus = MockDataProvider::customer();
        $cus->setId($customerId);
        return $cus;
    }
}
