<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Models\CreateInvoiceRequest;
use PagarmeApiSDKLib\Models\GetInvoiceResponse;
use PagarmeApiSDKLib\Models\ListInvoicesResponse;
use PagarmeApiSDKLib\Models\UpdateInvoiceStatusRequest;
use PagarmeApiSDKLib\Models\UpdateMetadataRequest;
use PagarmeApiSDKLib\Mock\MockDataProvider;
use PagarmeApiSDKLib\Mock\MockWebhookDispatcher;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class InvoicesController extends BaseController
{
    /**
     * Gets all invoices
     *
     * @param int|null $page Page number
     * @param int|null $size Page size
     * @param string|null $code Filter for Invoice's code
     * @param string|null $customerId Filter for Invoice's customer id
     * @param string|null $subscriptionId Filter for Invoice's subscription id
     * @param \DateTime|null $createdSince Filter for Invoice's creation date start range
     * @param \DateTime|null $createdUntil Filter for Invoices creation date end range
     * @param string|null $status Filter for Invoice's status
     * @param \DateTime|null $dueSince Filter for Invoice's due date start range
     * @param \DateTime|null $dueUntil Filter for Invoice's due date end range
     * @param string|null $customerDocument
     *
     * @return ListInvoicesResponse Response from the API call
     */
    public function getInvoices(
        ?int $page = null,
        ?int $size = null,
        ?string $code = null,
        ?string $customerId = null,
        ?string $subscriptionId = null,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null,
        ?string $status = null,
        ?\DateTime $dueSince = null,
        ?\DateTime $dueUntil = null,
        ?string $customerDocument = null
    ): ListInvoicesResponse {
        $invoice1 = MockDataProvider::invoice(10000, null, null, $subscriptionId);
        $invoice2 = MockDataProvider::invoice(20000, null, null, $subscriptionId);
        return MockDataProvider::listInvoices([$invoice1, $invoice2], 2);
    }

    /**
     * Cancels an invoice
     *
     * @param string $invoiceId Invoice id
     * @param string|null $idempotencyKey
     *
     * @return GetInvoiceResponse Response from the API call
     */
    public function cancelInvoice(string $invoiceId, ?string $idempotencyKey = null): GetInvoiceResponse
    {
        $invoice = MockDataProvider::invoice(10000, 'canceled');
        $invoice->setId($invoiceId);
        return $invoice;
    }

    /**
     * Updates the status from an invoice
     *
     * @param string $invoiceId Invoice Id
     * @param UpdateInvoiceStatusRequest $request Request for updating an invoice's status
     * @param string|null $idempotencyKey
     *
     * @return GetInvoiceResponse Response from the API call
     */
    public function updateInvoiceStatus(
        string $invoiceId,
        UpdateInvoiceStatusRequest $request,
        ?string $idempotencyKey = null
    ): GetInvoiceResponse {
        $invoice = MockDataProvider::invoice();
        $invoice->setId($invoiceId);
        $invoice->setStatus($request->getStatus());
        return $invoice;
    }

    /**
     * Updates the metadata from an invoice
     *
     * @param string $invoiceId The invoice id
     * @param UpdateMetadataRequest $request Request for updating the invoice metadata
     * @param string|null $idempotencyKey
     *
     * @return GetInvoiceResponse Response from the API call
     */
    public function updateInvoiceMetadata(
        string $invoiceId,
        UpdateMetadataRequest $request,
        ?string $idempotencyKey = null
    ): GetInvoiceResponse {
        $invoice = MockDataProvider::invoice();
        $invoice->setId($invoiceId);
        $invoice->setMetadata($request->getMetadata() ?? []);
        return $invoice;
    }

    /**
     * @param string $subscriptionId Subscription Id
     *
     * @return GetInvoiceResponse Response from the API call
     */
    public function getPartialInvoice(string $subscriptionId): GetInvoiceResponse
    {
        $invoice = MockDataProvider::invoice(10000, 'partial', null, $subscriptionId);
        return $invoice;
    }

    /**
     * Create an Invoice
     *
     * @param string $subscriptionId Subscription Id
     * @param string $cycleId Cycle Id
     * @param CreateInvoiceRequest|null $request
     * @param string|null $idempotencyKey
     *
     * @return GetInvoiceResponse Response from the API call
     */
    public function createInvoice(
        string $subscriptionId,
        string $cycleId,
        ?CreateInvoiceRequest $request = null,
        ?string $idempotencyKey = null
    ): GetInvoiceResponse {
        $invoice = MockDataProvider::invoice(10000, 'paid', null, $subscriptionId);

        MockWebhookDispatcher::dispatchInvoiceCreated([
            'id' => $invoice->getId(),
            'code' => $invoice->getCode(),
            'amount' => $invoice->getAmount(),
            'status' => $invoice->getStatus(),
            'subscription_id' => $subscriptionId,
        ]);

        return $invoice;
    }

    /**
     * Gets an invoice
     *
     * @param string $invoiceId Invoice Id
     *
     * @return GetInvoiceResponse Response from the API call
     */
    public function getInvoice(string $invoiceId): GetInvoiceResponse
    {
        $invoice = MockDataProvider::invoice();
        $invoice->setId($invoiceId);
        return $invoice;
    }
}
