<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Models\CreateOrderItemRequest;
use PagarmeApiSDKLib\Models\CreateOrderRequest;
use PagarmeApiSDKLib\Models\GetOrderItemResponse;
use PagarmeApiSDKLib\Models\GetOrderResponse;
use PagarmeApiSDKLib\Models\ListOrderResponse;
use PagarmeApiSDKLib\Models\UpdateMetadataRequest;
use PagarmeApiSDKLib\Models\UpdateOrderItemRequest;
use PagarmeApiSDKLib\Models\UpdateOrderStatusRequest;
use PagarmeApiSDKLib\Mock\MockDataProvider;
use PagarmeApiSDKLib\Mock\MockWebhookDispatcher;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class OrdersController extends BaseController
{
    /**
     * @param string $orderId Order Id
     * @param string|null $idempotencyKey
     *
     * @return GetOrderResponse Response from the API call
     */
    public function deleteAllOrderItems(string $orderId, ?string $idempotencyKey = null): GetOrderResponse
    {
        $order = MockDataProvider::order();
        $order->setId($orderId);
        $order->setItems([]);
        return $order;
    }

    /**
     * @param string $orderId Order Id
     * @param string $itemId Item Id
     *
     * @return GetOrderItemResponse Response from the API call
     */
    public function getOrderItem(string $orderId, string $itemId): GetOrderItemResponse
    {
        $item = MockDataProvider::orderItem();
        $item->setId($itemId);
        return $item;
    }

    /**
     * Updates the metadata from an order
     *
     * @param string $orderId The order id
     * @param UpdateMetadataRequest $request Request for updating the order metadata
     * @param string|null $idempotencyKey
     *
     * @return GetOrderResponse Response from the API call
     */
    public function updateOrderMetadata(
        string $orderId,
        UpdateMetadataRequest $request,
        ?string $idempotencyKey = null
    ): GetOrderResponse {
        $order = MockDataProvider::order();
        $order->setId($orderId);
        $order->setMetadata($request->getMetadata() ?? []);
        return $order;
    }

    /**
     * @param string $orderId Order Id
     * @param string $itemId Item Id
     * @param string|null $idempotencyKey
     *
     * @return GetOrderItemResponse Response from the API call
     */
    public function deleteOrderItem(
        string $orderId,
        string $itemId,
        ?string $idempotencyKey = null
    ): GetOrderItemResponse {
        $item = MockDataProvider::orderItem();
        $item->setId($itemId);
        $item->setStatus('deleted');
        return $item;
    }

    /**
     * Gets an order
     *
     * @param string $orderId Order id
     *
     * @return GetOrderResponse Response from the API call
     */
    public function getOrder(string $orderId): GetOrderResponse
    {
        $order = MockDataProvider::order();
        $order->setId($orderId);
        return $order;
    }

    /**
     * Gets all orders
     *
     * @param int|null $page Page number
     * @param int|null $size Page size
     * @param string|null $code Filter for order's code
     * @param string|null $status Filter for order's status
     * @param \DateTime|null $createdSince Filter for order's creation date start range
     * @param \DateTime|null $createdUntil Filter for order's creation date end range
     * @param string|null $customerId Filter for order's customer id
     *
     * @return ListOrderResponse Response from the API call
     */
    public function getOrders(
        ?int $page = null,
        ?int $size = null,
        ?string $code = null,
        ?string $status = null,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null,
        ?string $customerId = null
    ): ListOrderResponse {
        $order1 = MockDataProvider::order();
        $order2 = MockDataProvider::order();
        return MockDataProvider::listOrders([$order1, $order2], 2);
    }

    /**
     * @param string $orderId Order Id
     * @param string $itemId Item Id
     * @param UpdateOrderItemRequest $request Item Model
     * @param string|null $idempotencyKey
     *
     * @return GetOrderItemResponse Response from the API call
     */
    public function updateOrderItem(
        string $orderId,
        string $itemId,
        UpdateOrderItemRequest $request,
        ?string $idempotencyKey = null
    ): GetOrderItemResponse {
        $item = MockDataProvider::orderItem();
        $item->setId($itemId);
        return $item;
    }

    /**
     * @param string $id Order Id
     * @param UpdateOrderStatusRequest $request Update Order Model
     * @param string|null $idempotencyKey
     *
     * @return GetOrderResponse Response from the API call
     */
    public function closeOrder(
        string $id,
        UpdateOrderStatusRequest $request,
        ?string $idempotencyKey = null
    ): GetOrderResponse {
        $order = MockDataProvider::order();
        $order->setId($id);
        $order->setClosed(true);
        $order->setStatus('closed');
        return $order;
    }

    /**
     * Creates a new Order
     *
     * @param CreateOrderRequest $body Request for creating an order
     * @param string|null $idempotencyKey
     *
     * @return GetOrderResponse Response from the API call
     */
    public function createOrder(CreateOrderRequest $body, ?string $idempotencyKey = null): GetOrderResponse
    {
        $customer = $body->getCustomer() ? MockDataProvider::customer(
            $body->getCustomer()->getName(),
            $body->getCustomer()->getEmail(),
            $body->getCustomer()->getDocument(),
            $body->getCustomer()->getCode(),
            $body->getCustomer()->getType()
        ) : null;

        $metadata = $body->getMetadata();
        $code = $body->getCode();

        $order = MockDataProvider::order(
            10000,
            'paid',
            $customer,
            null,
            null,
            $metadata,
            $code
        );

        MockWebhookDispatcher::dispatchOrderPaid([
            'id' => $order->getId(),
            'code' => $order->getCode(),
            'amount' => $order->getAmount(),
            'status' => $order->getStatus(),
        ]);

        return $order;
    }

    /**
     * @param string $orderId Order Id
     * @param CreateOrderItemRequest $request Order Item Model
     * @param string|null $idempotencyKey
     *
     * @return GetOrderItemResponse Response from the API call
     */
    public function createOrderItem(
        string $orderId,
        CreateOrderItemRequest $request,
        ?string $idempotencyKey = null
    ): GetOrderItemResponse {
        $item = MockDataProvider::orderItem(
            $request->getDescription(),
            $request->getAmount(),
            $request->getQuantity(),
            $request->getCode() ?? ''
        );
        return $item;
    }
}
