<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Models\GetPayableResponse;
use PagarmeApiSDKLib\Models\ListPayablesResponse;
use PagarmeApiSDKLib\Mock\MockDataProvider;
use PagarmeApiSDKLib\Mock\MockWebhookDispatcher;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class PayablesController extends BaseController
{
    /**
     * @param string|null $type
     * @param string|null $splitId
     * @param string|null $bulkAnticipationId
     * @param int|null $installment
     * @param string|null $status
     * @param string|null $recipientId
     * @param int|null $amount
     * @param string|null $chargeId
     * @param string|null $paymentDateUntil
     * @param \DateTime|null $paymentDateSince
     * @param \DateTime|null $updatedUntil
     * @param \DateTime|null $updatedSince
     * @param \DateTime|null $createdUntil
     * @param \DateTime|null $createdSince
     * @param string|null $liquidationArrangementId
     * @param int|null $page
     * @param int|null $size
     * @param int|null $gatewayId
     *
     * @return ListPayablesResponse Response from the API call
     */
    public function getPayables(
        ?string $type = null,
        ?string $splitId = null,
        ?string $bulkAnticipationId = null,
        ?int $installment = null,
        ?string $status = null,
        ?string $recipientId = null,
        ?int $amount = null,
        ?string $chargeId = null,
        ?string $paymentDateUntil = null,
        ?\DateTime $paymentDateSince = null,
        ?\DateTime $updatedUntil = null,
        ?\DateTime $updatedSince = null,
        ?\DateTime $createdUntil = null,
        ?\DateTime $createdSince = null,
        ?string $liquidationArrangementId = null,
        ?int $page = null,
        ?int $size = null,
        ?int $gatewayId = null
    ): ListPayablesResponse {
        $payable1 = MockDataProvider::payable();
        $payable2 = MockDataProvider::payable();
        return MockDataProvider::listPayables([$payable1, $payable2], 2);
    }

    /**
     * @param int $id
     *
     * @return GetPayableResponse Response from the API call
     */
    public function getPayableById(int $id): GetPayableResponse
    {
        $payable = MockDataProvider::payable();
        $payable->setId((string) $id);
        return $payable;
    }
}
