<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Models\CreatePlanItemRequest;
use PagarmeApiSDKLib\Models\CreatePlanRequest;
use PagarmeApiSDKLib\Models\GetPlanItemResponse;
use PagarmeApiSDKLib\Models\GetPlanResponse;
use PagarmeApiSDKLib\Models\ListPlansResponse;
use PagarmeApiSDKLib\Models\UpdateMetadataRequest;
use PagarmeApiSDKLib\Models\UpdatePlanItemRequest;
use PagarmeApiSDKLib\Models\UpdatePlanRequest;
use PagarmeApiSDKLib\Mock\MockDataProvider;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class PlansController extends BaseController
{
    /**
     * Gets a plan
     *
     * @param string $planId Plan id
     *
     * @return GetPlanResponse Response from the API call
     */
    public function getPlan(string $planId): GetPlanResponse
    {
        $plan = MockDataProvider::plan();
        $plan->setId($planId);
        return $plan;
    }

    /**
     * Removes an item from a plan
     *
     * @param string $planId Plan id
     * @param string $planItemId Plan item id
     * @param string|null $idempotencyKey
     *
     * @return GetPlanItemResponse Response from the API call
     */
    public function deletePlanItem(
        string $planId,
        string $planItemId,
        ?string $idempotencyKey = null
    ): GetPlanItemResponse {
        $item = MockDataProvider::planItem();
        $item->setId($planItemId);
        $item->setStatus('deleted');
        return $item;
    }

    /**
     * Updates the metadata from a plan
     *
     * @param string $planId The plan id
     * @param UpdateMetadataRequest $request Request for updating the plan metadata
     * @param string|null $idempotencyKey
     *
     * @return GetPlanResponse Response from the API call
     */
    public function updatePlanMetadata(
        string $planId,
        UpdateMetadataRequest $request,
        ?string $idempotencyKey = null
    ): GetPlanResponse {
        $plan = MockDataProvider::plan(null, null, null, null, $request->getMetadata());
        $plan->setId($planId);
        return $plan;
    }

    /**
     * Creates a new plan
     *
     * @param CreatePlanRequest $body Request for creating a plan
     * @param string|null $idempotencyKey
     *
     * @return GetPlanResponse Response from the API call
     */
    public function createPlan(CreatePlanRequest $body, ?string $idempotencyKey = null): GetPlanResponse
    {
        return MockDataProvider::plan(
            $body->getName(),
            $body->getInterval(),
            $body->getIntervalCount(),
            null,
            $body->getMetadata()
        );
    }

    /**
     * Updates a plan
     *
     * @param string $planId Plan id
     * @param UpdatePlanRequest $request Request for updating a plan
     * @param string|null $idempotencyKey
     *
     * @return GetPlanResponse Response from the API call
     */
    public function updatePlan(
        string $planId,
        UpdatePlanRequest $request,
        ?string $idempotencyKey = null
    ): GetPlanResponse {
        $plan = MockDataProvider::plan();
        $plan->setId($planId);
        return $plan;
    }

    /**
     * Deletes a plan
     *
     * @param string $planId Plan id
     * @param string|null $idempotencyKey
     *
     * @return GetPlanResponse Response from the API call
     */
    public function deletePlan(string $planId, ?string $idempotencyKey = null): GetPlanResponse
    {
        $plan = MockDataProvider::plan();
        $plan->setId($planId);
        $plan->setStatus('deleted');
        return $plan;
    }

    /**
     * Gets all plans
     *
     * @param int|null $page Page number
     * @param int|null $size Page size
     * @param string|null $name Filter for Plan's name
     * @param string|null $status Filter for Plan's status
     * @param string|null $billingType Filter for plan's billing type
     * @param \DateTime|null $createdSince Filter for plan's creation date start range
     * @param \DateTime|null $createdUntil Filter for plan's creation date end range
     *
     * @return ListPlansResponse Response from the API call
     */
    public function getPlans(
        ?int $page = null,
        ?int $size = null,
        ?string $name = null,
        ?string $status = null,
        ?string $billingType = null,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null
    ): ListPlansResponse {
        return MockDataProvider::listPlans([
            MockDataProvider::plan('Mock Plan 1'),
            MockDataProvider::plan('Mock Plan 2'),
        ], 2);
    }

    /**
     * Updates a plan item
     *
     * @param string $planId Plan id
     * @param string $planItemId Plan item id
     * @param UpdatePlanItemRequest $body Request for updating the plan item
     * @param string|null $idempotencyKey
     *
     * @return GetPlanItemResponse Response from the API call
     */
    public function updatePlanItem(
        string $planId,
        string $planItemId,
        UpdatePlanItemRequest $body,
        ?string $idempotencyKey = null
    ): GetPlanItemResponse {
        $item = MockDataProvider::planItem();
        $item->setId($planItemId);
        return $item;
    }

    /**
     * Adds a new item to a plan
     *
     * @param string $planId Plan id
     * @param CreatePlanItemRequest $request Request for creating a plan item
     * @param string|null $idempotencyKey
     *
     * @return GetPlanItemResponse Response from the API call
     */
    public function createPlanItem(
        string $planId,
        CreatePlanItemRequest $request,
        ?string $idempotencyKey = null
    ): GetPlanItemResponse {
        return MockDataProvider::planItem();
    }

    /**
     * Gets a plan item
     *
     * @param string $planId Plan id
     * @param string $planItemId Plan item id
     *
     * @return GetPlanItemResponse Response from the API call
     */
    public function getPlanItem(string $planId, string $planItemId): GetPlanItemResponse
    {
        $item = MockDataProvider::planItem();
        $item->setId($planItemId);
        return $item;
    }
}
