<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use DateTime;
use PagarmeApiSDKLib\Models\CreateAnticipationRequest;
use PagarmeApiSDKLib\Models\CreateKYCLinkResponse;
use PagarmeApiSDKLib\Models\CreateRecipientRequest;
use PagarmeApiSDKLib\Models\CreateTransferRequest;
use PagarmeApiSDKLib\Models\CreateWithdrawRequest;
use PagarmeApiSDKLib\Models\GetAnticipationLimitResponse;
use PagarmeApiSDKLib\Models\GetAnticipationResponse;
use PagarmeApiSDKLib\Models\GetBalanceResponse;
use PagarmeApiSDKLib\Models\GetRecipientResponse;
use PagarmeApiSDKLib\Models\GetTransferResponse;
use PagarmeApiSDKLib\Models\GetWithdrawResponse;
use PagarmeApiSDKLib\Models\ListAnticipationResponse;
use PagarmeApiSDKLib\Models\ListRecipientResponse;
use PagarmeApiSDKLib\Models\ListTransferResponse;
use PagarmeApiSDKLib\Models\ListWithdrawals;
use PagarmeApiSDKLib\Models\PagingResponse;
use PagarmeApiSDKLib\Models\UpdateAutomaticAnticipationSettingsRequest;
use PagarmeApiSDKLib\Models\UpdateMetadataRequest;
use PagarmeApiSDKLib\Models\UpdateRecipientBankAccountRequest;
use PagarmeApiSDKLib\Models\UpdateRecipientCodeRequest;
use PagarmeApiSDKLib\Models\UpdateRecipientRequest;
use PagarmeApiSDKLib\Models\UpdateTransferSettingsRequest;
use PagarmeApiSDKLib\Mock\MockDataProvider;
use PagarmeApiSDKLib\Mock\MockWebhookDispatcher;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class RecipientsController extends BaseController
{
    /**
     * Updates a recipient
     *
     * @param string $recipientId Recipient id
     * @param UpdateRecipientRequest $request Recipient data
     * @param string|null $idempotencyKey
     *
     * @return GetRecipientResponse Response from the API call
     */
    public function updateRecipient(
        string $recipientId,
        UpdateRecipientRequest $request,
        ?string $idempotencyKey = null
    ): GetRecipientResponse {
        $rec = MockDataProvider::recipient();
        $rec->setId($recipientId);
        return $rec;
    }

    /**
     * @param string $recipientId
     * @param string $withdrawalId
     *
     * @return GetWithdrawResponse Response from the API call
     */
    public function getWithdrawById(string $recipientId, string $withdrawalId): GetWithdrawResponse
    {
        $withdraw = new GetWithdrawResponse();
        $withdraw->setId($withdrawalId);
        $withdraw->setGatewayId(MockIdGenerator::generate('gw'));
        $withdraw->setAmount(50000);
        $withdraw->setStatus('transferred');
        $withdraw->setCreatedAt(new DateTime());
        $withdraw->setUpdatedAt(new DateTime());
        return $withdraw;
    }

    /**
     * Retrieves recipient information
     *
     * @param string $recipientId Recipiend id
     *
     * @return GetRecipientResponse Response from the API call
     */
    public function getRecipient(string $recipientId): GetRecipientResponse
    {
        $rec = MockDataProvider::recipient();
        $rec->setId($recipientId);
        return $rec;
    }

    /**
     * Get balance information for a recipient
     *
     * @param string $recipientId Recipient id
     *
     * @return GetBalanceResponse Response from the API call
     */
    public function getBalance(string $recipientId): GetBalanceResponse
    {
        return MockDataProvider::balance($recipientId);
    }

    /**
     * Retrieves paginated recipients information
     *
     * @param int|null $page Page number
     * @param int|null $size Page size
     *
     * @return ListRecipientResponse Response from the API call
     */
    public function getRecipients(?int $page = null, ?int $size = null): ListRecipientResponse
    {
        $rec1 = MockDataProvider::recipient();
        $rec2 = MockDataProvider::recipient();
        return MockDataProvider::listRecipients([$rec1, $rec2], 2);
    }

    /**
     * Updates the default bank account from a recipient
     *
     * @param string $recipientId Recipient id
     * @param UpdateRecipientBankAccountRequest $request Bank account data
     * @param string|null $idempotencyKey
     *
     * @return GetRecipientResponse Response from the API call
     */
    public function updateRecipientDefaultBankAccount(
        string $recipientId,
        UpdateRecipientBankAccountRequest $request,
        ?string $idempotencyKey = null
    ): GetRecipientResponse {
        $rec = MockDataProvider::recipient();
        $rec->setId($recipientId);
        return $rec;
    }

    /**
     * Gets a paginated list of transfers for the recipient
     *
     * @param string $recipientId Recipient id
     * @param int|null $page Page number
     * @param int|null $size Page size
     * @param string|null $status Filter for transfer status
     * @param \DateTime|null $createdSince Filter for start range of transfer creation date
     * @param \DateTime|null $createdUntil Filter for end range of transfer creation date
     *
     * @return ListTransferResponse Response from the API call
     */
    public function getTransfers(
        string $recipientId,
        ?int $page = null,
        ?int $size = null,
        ?string $status = null,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null
    ): ListTransferResponse {
        $transfer = new GetTransferResponse();
        $transfer->setId(MockIdGenerator::generate('tr'));
        $transfer->setAmount(50000);
        $transfer->setStatus('transferred');
        $transfer->setCreatedAt(new DateTime());
        $transfer->setUpdatedAt(new DateTime());

        $list = new ListTransferResponse();
        $list->setData([$transfer]);
        $list->setPaging(MockDataProvider::paging(1));
        return $list;
    }

    /**
     * Gets a transfer
     *
     * @param string $recipientId Recipient id
     * @param string $transferId Transfer id
     *
     * @return GetTransferResponse Response from the API call
     */
    public function getTransfer(string $recipientId, string $transferId): GetTransferResponse
    {
        $transfer = new GetTransferResponse();
        $transfer->setId($transferId);
        $transfer->setAmount(50000);
        $transfer->setStatus('transferred');
        $transfer->setCreatedAt(new DateTime());
        $transfer->setUpdatedAt(new DateTime());
        return $transfer;
    }

    /**
     * @param string $recipientId
     * @param CreateWithdrawRequest $request
     *
     * @return GetWithdrawResponse Response from the API call
     */
    public function createWithdraw(string $recipientId, CreateWithdrawRequest $request): GetWithdrawResponse
    {
        $withdraw = new GetWithdrawResponse();
        $withdraw->setId(MockIdGenerator::generate('withdraw'));
        $withdraw->setGatewayId(MockIdGenerator::generate('gw'));
        $withdraw->setAmount($request->getAmount());
        $withdraw->setStatus('pending');
        $withdraw->setCreatedAt(new DateTime());
        $withdraw->setUpdatedAt(new DateTime());
        return $withdraw;
    }

    /**
     * Gets an anticipation
     *
     * @param string $recipientId Recipient id
     * @param string $anticipationId Anticipation id
     *
     * @return GetAnticipationResponse Response from the API call
     */
    public function getAnticipation(string $recipientId, string $anticipationId): GetAnticipationResponse
    {
        $anticipation = new GetAnticipationResponse();
        $anticipation->setId($anticipationId);
        $anticipation->setRequestedAmount(100000);
        $anticipation->setApprovedAmount(100000);
        $anticipation->setStatus('approved');
        $anticipation->setTimeframe('start');
        $anticipation->setCreatedAt(new DateTime());
        $anticipation->setUpdatedAt(new DateTime());
        $anticipation->setPaymentDate(new DateTime());
        return $anticipation;
    }

    /**
     * @param string $recipientId Recipient Identificator
     * @param UpdateTransferSettingsRequest $request
     * @param string|null $idempotencyKey
     *
     * @return GetRecipientResponse Response from the API call
     */
    public function updateRecipientTransferSettings(
        string $recipientId,
        UpdateTransferSettingsRequest $request,
        ?string $idempotencyKey = null
    ): GetRecipientResponse {
        $rec = MockDataProvider::recipient();
        $rec->setId($recipientId);
        return $rec;
    }

    /**
     * Retrieves recipient information
     *
     * @param string $code Recipient code
     *
     * @return GetRecipientResponse Response from the API call
     */
    public function getRecipientByCode(string $code): GetRecipientResponse
    {
        $rec = MockDataProvider::recipient();
        return $rec;
    }

    /**
     * Updates recipient metadata
     *
     * @param string $recipientId Recipient id
     * @param UpdateAutomaticAnticipationSettingsRequest $request Metadata
     * @param string|null $idempotencyKey
     *
     * @return GetRecipientResponse Response from the API call
     */
    public function updateAutomaticAnticipationSettings(
        string $recipientId,
        UpdateAutomaticAnticipationSettingsRequest $request,
        ?string $idempotencyKey = null
    ): GetRecipientResponse {
        $rec = MockDataProvider::recipient();
        $rec->setId($recipientId);
        return $rec;
    }

    /**
     * Creates a transfer for a recipient
     *
     * @param string $recipientId Recipient Id
     * @param CreateTransferRequest $request Transfer data
     * @param string|null $idempotencyKey
     *
     * @return GetTransferResponse Response from the API call
     */
    public function createTransfer(
        string $recipientId,
        CreateTransferRequest $request,
        ?string $idempotencyKey = null
    ): GetTransferResponse {
        $transfer = new GetTransferResponse();
        $transfer->setId(MockIdGenerator::generate('tr'));
        $transfer->setAmount($request->getAmount());
        $transfer->setStatus('pending');
        $transfer->setCreatedAt(new DateTime());
        $transfer->setUpdatedAt(new DateTime());
        return $transfer;
    }

    /**
     * Creates a new recipient
     *
     * @param CreateRecipientRequest $request Recipient data
     * @param string|null $idempotencyKey
     *
     * @return GetRecipientResponse Response from the API call
     */
    public function createRecipient(
        CreateRecipientRequest $request,
        ?string $idempotencyKey = null
    ): GetRecipientResponse {
        $rec = MockDataProvider::recipient();
        return $rec;
    }

    /**
     * @return GetRecipientResponse Response from the API call
     */
    public function getDefaultRecipient(): GetRecipientResponse
    {
        $rec = MockDataProvider::recipient();
        $rec->setName('Default Mock Recipient');
        return $rec;
    }

    /**
     * Creates an anticipation
     *
     * @param string $recipientId Recipient id
     * @param CreateAnticipationRequest $request Anticipation data
     * @param string|null $idempotencyKey
     *
     * @return GetAnticipationResponse Response from the API call
     */
    public function createAnticipation(
        string $recipientId,
        CreateAnticipationRequest $request,
        ?string $idempotencyKey = null
    ): GetAnticipationResponse {
        $anticipation = new GetAnticipationResponse();
        $anticipation->setId(MockIdGenerator::generate('antcp'));
        $anticipation->setRequestedAmount($request->getAmount());
        $anticipation->setApprovedAmount($request->getAmount());
        $anticipation->setStatus('pending');
        $anticipation->setTimeframe($request->getTimeframe());
        $anticipation->setCreatedAt(new DateTime());
        $anticipation->setUpdatedAt(new DateTime());
        $anticipation->setPaymentDate($request->getPaymentDate());
        return $anticipation;
    }

    /**
     * Gets the anticipation limits for a recipient
     *
     * @param string $recipientId Recipient id
     * @param string $timeframe Timeframe
     * @param \DateTime $paymentDate Anticipation payment date
     *
     * @return GetAnticipationLimitResponse Response from the API call
     */
    public function getAnticipationLimits(
        string $recipientId,
        string $timeframe,
        \DateTime $paymentDate
    ): GetAnticipationLimitResponse {
        $limit = new GetAnticipationLimitResponse();
        $limit->setAmount(500000);
        $limit->setAnticipationFee(350);
        return $limit;
    }

    /**
     * Updates recipient metadata
     *
     * @param string $recipientId Recipient id
     * @param UpdateMetadataRequest $request Metadata
     * @param string|null $idempotencyKey
     *
     * @return GetRecipientResponse Response from the API call
     */
    public function updateRecipientMetadata(
        string $recipientId,
        UpdateMetadataRequest $request,
        ?string $idempotencyKey = null
    ): GetRecipientResponse {
        $rec = MockDataProvider::recipient();
        $rec->setId($recipientId);
        return $rec;
    }

    /**
     * Retrieves a paginated list of anticipations from a recipient
     *
     * @param string $recipientId Recipient id
     * @param int|null $page Page number
     * @param int|null $size Page size
     * @param string|null $status Filter for anticipation status
     * @param string|null $timeframe Filter for anticipation timeframe
     * @param \DateTime|null $paymentDateSince Filter for start range for anticipation payment date
     * @param \DateTime|null $paymentDateUntil Filter for end range for anticipation payment date
     * @param \DateTime|null $createdSince Filter for start range for anticipation creation date
     * @param \DateTime|null $createdUntil Filter for end range for anticipation creation date
     *
     * @return ListAnticipationResponse Response from the API call
     */
    public function getAnticipations(
        string $recipientId,
        ?int $page = null,
        ?int $size = null,
        ?string $status = null,
        ?string $timeframe = null,
        ?\DateTime $paymentDateSince = null,
        ?\DateTime $paymentDateUntil = null,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null
    ): ListAnticipationResponse {
        $anticipation = new GetAnticipationResponse();
        $anticipation->setId(MockIdGenerator::generate('antcp'));
        $anticipation->setRequestedAmount(100000);
        $anticipation->setApprovedAmount(100000);
        $anticipation->setStatus('approved');
        $anticipation->setTimeframe('start');
        $anticipation->setCreatedAt(new DateTime());
        $anticipation->setUpdatedAt(new DateTime());
        $anticipation->setPaymentDate(new DateTime());

        $list = new ListAnticipationResponse();
        $list->setData([$anticipation]);
        $list->setPaging(MockDataProvider::paging(1));
        return $list;
    }

    /**
     * Gets a paginated list of transfers for the recipient
     *
     * @param string $recipientId
     * @param int|null $page
     * @param int|null $size
     * @param string|null $status
     * @param \DateTime|null $createdSince
     * @param \DateTime|null $createdUntil
     *
     * @return ListWithdrawals Response from the API call
     */
    public function getWithdrawals(
        string $recipientId,
        ?int $page = null,
        ?int $size = null,
        ?string $status = null,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null
    ): ListWithdrawals {
        $withdraw = new GetWithdrawResponse();
        $withdraw->setId(MockIdGenerator::generate('withdraw'));
        $withdraw->setGatewayId(MockIdGenerator::generate('gw'));
        $withdraw->setAmount(50000);
        $withdraw->setStatus('transferred');
        $withdraw->setCreatedAt(new DateTime());
        $withdraw->setUpdatedAt(new DateTime());

        $list = new ListWithdrawals();
        $list->setData([$withdraw]);
        $list->setPaging(MockDataProvider::paging(1));
        return $list;
    }

    /**
     * Create a KYC link
     *
     * @param string $recipientId Recipient id
     *
     * @return CreateKYCLinkResponse Response from the API call
     */
    public function createKYCLink(string $recipientId): CreateKYCLinkResponse
    {
        $kyc = new CreateKYCLinkResponse();
        $kyc->setBase64('bW9jay1reWMtYmFzZTY0LWRhdGE=');
        $kyc->setUrl('https://mock-kyc.pagarme.com/link/' . $recipientId);
        $kyc->setExpirationDate((new DateTime('+24 hours'))->format('Y-m-d\TH:i:s\Z'));
        return $kyc;
    }

    /**
     * Updates recipient code
     *
     * @param string $recipientId Recipient id
     * @param UpdateRecipientCodeRequest $request UpdateRecipientCodeRequest
     * @param string|null $idempotencyKey
     *
     * @return GetRecipientResponse Response from the API call
     */
    public function updateRecipientCode(
        string $recipientId,
        UpdateRecipientCodeRequest $request,
        ?string $idempotencyKey = null
    ): GetRecipientResponse {
        $rec = MockDataProvider::recipient();
        $rec->setId($recipientId);
        return $rec;
    }
}
