<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Exceptions\ApiException;
use PagarmeApiSDKLib\Models\CreateCancelSubscriptionRequest;
use PagarmeApiSDKLib\Models\CreateDiscountRequest;
use PagarmeApiSDKLib\Models\CreateIncrementRequest;
use PagarmeApiSDKLib\Models\CreateSubscriptionItemRequest;
use PagarmeApiSDKLib\Models\CreateSubscriptionRequest;
use PagarmeApiSDKLib\Models\CreateUsageRequest;
use PagarmeApiSDKLib\Models\GetDiscountResponse;
use PagarmeApiSDKLib\Models\GetIncrementResponse;
use PagarmeApiSDKLib\Models\GetPeriodResponse;
use PagarmeApiSDKLib\Models\GetSubscriptionItemResponse;
use PagarmeApiSDKLib\Models\GetSubscriptionResponse;
use PagarmeApiSDKLib\Models\GetUsageReportResponse;
use PagarmeApiSDKLib\Models\GetUsageResponse;
use PagarmeApiSDKLib\Models\ListCyclesResponse;
use PagarmeApiSDKLib\Models\ListDiscountsResponse;
use PagarmeApiSDKLib\Models\ListIncrementsResponse;
use PagarmeApiSDKLib\Models\ListSubscriptionItemsResponse;
use PagarmeApiSDKLib\Models\ListSubscriptionsResponse;
use PagarmeApiSDKLib\Models\ListUsagesResponse;
use PagarmeApiSDKLib\Models\PagingResponse;
use PagarmeApiSDKLib\Models\UpdateCurrentCycleEndDateRequest;
use PagarmeApiSDKLib\Models\UpdateCurrentCycleStatusRequest;
use PagarmeApiSDKLib\Models\UpdateMetadataRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionAffiliationIdRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionBillingDateRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionCardRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionDueDaysRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionItemRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionMinimumPriceRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionPaymentMethodRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionSplitRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionStartAtRequest;
use PagarmeApiSDKLib\Mock\MockDataProvider;
use PagarmeApiSDKLib\Mock\MockWebhookDispatcher;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class SubscriptionsController extends BaseController
{
    /**
     * Updates the credit card from a subscription
     *
     * @param string $subscriptionId Subscription id
     * @param UpdateSubscriptionCardRequest $request Request for updating a card
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSubscriptionCard(
        string $subscriptionId,
        UpdateSubscriptionCardRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        $sub->setStatus('active');
        return $sub;
    }

    /**
     * Creates a discount
     *
     * @param string $subscriptionId Subscription id
     * @param CreateDiscountRequest $request Request for creating a discount
     * @param string|null $idempotencyKey
     *
     * @return GetDiscountResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createDiscount(
        string $subscriptionId,
        CreateDiscountRequest $request,
        ?string $idempotencyKey = null
    ): GetDiscountResponse {
        $discount = new GetDiscountResponse();
        $discount->setId(MockIdGenerator::generate('disc'));
        $discount->setStatus('active');
        $discount->setValue(10.0);
        $discount->setDiscountType('percentage');
        $discount->setCreatedAt(new \DateTime());
        $discount->setCycles(0);
        $discount->setDescription('Mock discount');
        return $discount;
    }

    /**
     * Updates the billing date from a subscription
     *
     * @param string $subscriptionId The subscription id
     * @param UpdateSubscriptionBillingDateRequest $request Request for updating the subscription
     *        billing date
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSubscriptionBillingDate(
        string $subscriptionId,
        UpdateSubscriptionBillingDateRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        return $sub;
    }

    /**
     * Updates the start at date from a subscription
     *
     * @param string $subscriptionId The subscription id
     * @param UpdateSubscriptionStartAtRequest $request Request for updating the subscription start
     *        date
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSubscriptionStartAt(
        string $subscriptionId,
        UpdateSubscriptionStartAtRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        return $sub;
    }

    /**
     * Gets a subscription
     *
     * @param string $subscriptionId Subscription id
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getSubscription(string $subscriptionId): GetSubscriptionResponse
    {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        return $sub;
    }

    /**
     * Lists all usages from a subscription item
     *
     * @param string $subscriptionId The subscription id
     * @param string $itemId The subscription item id
     * @param int|null $page Page number
     * @param int|null $size Page size
     * @param string|null $code Identification code in the client system
     * @param string|null $group Identification group in the client system
     * @param \DateTime|null $usedSince
     * @param \DateTime|null $usedUntil
     *
     * @return ListUsagesResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getUsages(
        string $subscriptionId,
        string $itemId,
        ?int $page = null,
        ?int $size = null,
        ?string $code = null,
        ?string $group = null,
        ?\DateTime $usedSince = null,
        ?\DateTime $usedUntil = null
    ): ListUsagesResponse {
        $usage = new GetUsageResponse();
        $usage->setId(MockIdGenerator::generate('usage'));
        $usage->setQuantity(1);
        $usage->setDescription('Mock usage');
        $usage->setUsedAt(new \DateTime());
        $usage->setCreatedAt(new \DateTime());
        $usage->setStatus('active');
        $usage->setCode($code ?? 'mock_usage_code');
        $usage->setGroup($group ?? 'default');
        $usage->setAmount(100);

        $list = new ListUsagesResponse();
        $list->setData([$usage]);
        $list->setPaging(MockDataProvider::paging(1));
        return $list;
    }

    /**
     * @param string $subscriptionId
     * @param UpdateCurrentCycleEndDateRequest $request Request for updating the end date of the
     *        current signature cycle
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateLatestPeriodEndAt(
        string $subscriptionId,
        UpdateCurrentCycleEndDateRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        return $sub;
    }

    /**
     * Deletes a discount
     *
     * @param string $subscriptionId Subscription id
     * @param string $discountId Discount Id
     * @param string|null $idempotencyKey
     *
     * @return GetDiscountResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function deleteDiscount(
        string $subscriptionId,
        string $discountId,
        ?string $idempotencyKey = null
    ): GetDiscountResponse {
        $discount = new GetDiscountResponse();
        $discount->setId($discountId);
        $discount->setStatus('deleted');
        $discount->setValue(10.0);
        $discount->setDiscountType('percentage');
        $discount->setCreatedAt(new \DateTime());
        $discount->setDeletedAt(new \DateTime());
        $discount->setDescription('Mock discount');
        return $discount;
    }

    /**
     * Updates the payment method from a subscription
     *
     * @param string $subscriptionId Subscription id
     * @param UpdateSubscriptionPaymentMethodRequest $request Request for updating the paymentmethod
     *        from a subscription
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSubscriptionPaymentMethod(
        string $subscriptionId,
        UpdateSubscriptionPaymentMethodRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        return $sub;
    }

    /**
     * Cancels a subscription
     *
     * @param string $subscriptionId Subscription id
     * @param CreateCancelSubscriptionRequest|null $request Request for cancelling a subscription
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cancelSubscription(
        string $subscriptionId,
        ?CreateCancelSubscriptionRequest $request = null,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        $sub->setStatus('canceled');
        $sub->setCanceledAt(new \DateTime());

        MockWebhookDispatcher::dispatchSubscriptionCanceled($sub);

        return $sub;
    }

    /**
     * Creates a new subscription
     *
     * @param CreateSubscriptionRequest $body Request for creating a subscription
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createSubscription(
        CreateSubscriptionRequest $body,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        // Extract customer info from body
        $customerReq = $body->getCustomer();
        $customerName = $customerReq ? $customerReq->getName() : null;
        $customerEmail = $customerReq ? $customerReq->getEmail() : null;
        $customerDocument = $customerReq ? $customerReq->getDocument() : null;

        $customer = MockDataProvider::customer($customerName, $customerEmail, $customerDocument);
        $card = MockDataProvider::card();

        $sub = MockDataProvider::subscription(
            $body->getPlanId(),
            $body->getPaymentMethod(),
            null,
            $customer,
            $card,
            null,
            $body->getMetadata(),
            $body->getCode(),
            $body->getStatementDescriptor(),
            $body->getInstallments() ?? 1,
            $body->getCycles(),
            $body->getInterval(),
            $body->getIntervalCount(),
            $body->getBillingType()
        );

        MockWebhookDispatcher::dispatchSubscriptionCreated($sub);

        return $sub;
    }

    /**
     * @param string $subscriptionId
     * @param UpdateSubscriptionAffiliationIdRequest $request Request for updating a subscription
     *        affiliation id
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSubscriptionAffiliationId(
        string $subscriptionId,
        UpdateSubscriptionAffiliationIdRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        return $sub;
    }

    /**
     * Atualização do valor minimo da assinatura
     *
     * @param string $subscriptionId Subscription Id
     * @param UpdateSubscriptionMinimumPriceRequest $request Request da requisição com o valor
     *        minimo que será configurado
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSubscriptionMiniumPrice(
        string $subscriptionId,
        UpdateSubscriptionMinimumPriceRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        return $sub;
    }

    /**
     * @param string $subscriptionId The subscription id
     * @param string $cycleId
     *
     * @return GetPeriodResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getSubscriptionCycleById(string $subscriptionId, string $cycleId): GetPeriodResponse
    {
        $period = MockDataProvider::period(1);
        $period->setId($cycleId);
        return $period;
    }

    /**
     * @param string $subscriptionId The subscription Id
     * @param string $periodId The period Id
     *
     * @return GetUsageReportResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getUsageReport(string $subscriptionId, string $periodId): GetUsageReportResponse
    {
        $report = new GetUsageReportResponse();
        $report->setUrl('https://mock.pagarme.com/usage-report/' . $subscriptionId . '/' . $periodId);
        $report->setUsageReportUrl('https://mock.pagarme.com/usage-report/' . $subscriptionId . '/' . $periodId . '/detail');
        $report->setGroupedReportUrl('https://mock.pagarme.com/usage-report/' . $subscriptionId . '/' . $periodId . '/grouped');
        return $report;
    }

    /**
     * @param string $subscriptionId
     * @param string|null $idempotencyKey
     *
     * @return GetPeriodResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function renewSubscription(string $subscriptionId, ?string $idempotencyKey = null): GetPeriodResponse
    {
        return MockDataProvider::period(2);
    }

    /**
     * Deletes a usage
     *
     * @param string $subscriptionId The subscription id
     * @param string $itemId The subscription item id
     * @param string $usageId The usage id
     * @param string|null $idempotencyKey
     *
     * @return GetUsageResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function deleteUsage(
        string $subscriptionId,
        string $itemId,
        string $usageId,
        ?string $idempotencyKey = null
    ): GetUsageResponse {
        $usage = new GetUsageResponse();
        $usage->setId($usageId);
        $usage->setQuantity(1);
        $usage->setDescription('Mock usage');
        $usage->setUsedAt(new \DateTime());
        $usage->setCreatedAt(new \DateTime());
        $usage->setStatus('deleted');
        $usage->setDeletedAt(new \DateTime());
        $usage->setCode('mock_usage_code');
        $usage->setAmount(100);
        return $usage;
    }

    /**
     * Create Usage
     *
     * @param string $subscriptionId Subscription id
     * @param string $itemId Item id
     * @param string|null $idempotencyKey
     *
     * @return GetUsageResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createAnUsage(
        string $subscriptionId,
        string $itemId,
        ?string $idempotencyKey = null
    ): GetUsageResponse {
        $usage = new GetUsageResponse();
        $usage->setId(MockIdGenerator::generate('usage'));
        $usage->setQuantity(1);
        $usage->setDescription('Mock usage');
        $usage->setUsedAt(new \DateTime());
        $usage->setCreatedAt(new \DateTime());
        $usage->setStatus('active');
        $usage->setCode('mock_usage_code');
        $usage->setAmount(100);
        return $usage;
    }

    /**
     * @param string $subscriptionId Subscription Id
     * @param UpdateCurrentCycleStatusRequest $request Request for updating the end date of the
     *        subscription current status
     * @param string|null $idempotencyKey
     *
     * @return void Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateCurrentCycleStatus(
        string $subscriptionId,
        UpdateCurrentCycleStatusRequest $request,
        ?string $idempotencyKey = null
    ): void {
        // Mock: no-op, just return
        return;
    }

    /**
     * Get Subscription Item
     *
     * @param string $subscriptionId Subscription Id
     * @param string $itemId Item id
     *
     * @return GetSubscriptionItemResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getSubscriptionItem(string $subscriptionId, string $itemId): GetSubscriptionItemResponse
    {
        $item = MockDataProvider::subscriptionItem();
        $item->setId($itemId);
        return $item;
    }

    /**
     * @param string $subscriptionId The subscription Id
     * @param string $incrementId The increment Id
     *
     * @return GetIncrementResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getIncrementById(string $subscriptionId, string $incrementId): GetIncrementResponse
    {
        $increment = new GetIncrementResponse();
        $increment->setId($incrementId);
        $increment->setValue(10.0);
        $increment->setIncrementType('percentage');
        $increment->setStatus('active');
        $increment->setCreatedAt(new \DateTime());
        $increment->setDescription('Mock increment');
        return $increment;
    }

    /**
     * Deletes a increment
     *
     * @param string $subscriptionId Subscription id
     * @param string $incrementId Increment id
     * @param string|null $idempotencyKey
     *
     * @return GetIncrementResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function deleteIncrement(
        string $subscriptionId,
        string $incrementId,
        ?string $idempotencyKey = null
    ): GetIncrementResponse {
        $increment = new GetIncrementResponse();
        $increment->setId($incrementId);
        $increment->setValue(10.0);
        $increment->setIncrementType('percentage');
        $increment->setStatus('deleted');
        $increment->setCreatedAt(new \DateTime());
        $increment->setDeletedAt(new \DateTime());
        $increment->setDescription('Mock increment');
        return $increment;
    }

    /**
     * @param string $subscriptionId The subscription id
     * @param int $page Page number
     * @param int $size Page size
     *
     * @return ListDiscountsResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getDiscounts(string $subscriptionId, int $page, int $size): ListDiscountsResponse
    {
        $discount = new GetDiscountResponse();
        $discount->setId(MockIdGenerator::generate('disc'));
        $discount->setStatus('active');
        $discount->setValue(10.0);
        $discount->setDiscountType('percentage');
        $discount->setCreatedAt(new \DateTime());
        $discount->setDescription('Mock discount');

        $list = new ListDiscountsResponse();
        $list->setData([$discount]);
        $list->setPaging(MockDataProvider::paging(1));
        return $list;
    }

    /**
     * Updates the boleto due days from a subscription
     *
     * @param string $subscriptionId Subscription Id
     * @param UpdateSubscriptionDueDaysRequest $request
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSubscriptionDueDays(
        string $subscriptionId,
        UpdateSubscriptionDueDaysRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        return $sub;
    }

    /**
     * Creates a new Subscription item
     *
     * @param string $subscriptionId Subscription id
     * @param CreateSubscriptionItemRequest $request Request for creating a subscription item
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionItemResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createSubscriptionItem(
        string $subscriptionId,
        CreateSubscriptionItemRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionItemResponse {
        return MockDataProvider::subscriptionItem();
    }

    /**
     * @param string $id Subscription's id
     * @param UpdateSubscriptionSplitRequest $request
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSplitSubscription(
        string $id,
        UpdateSubscriptionSplitRequest $request
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($id);
        return $sub;
    }

    /**
     * Get Subscription Items
     *
     * @param string $subscriptionId The subscription id
     * @param int|null $page Page number
     * @param int|null $size Page size
     * @param string|null $name The item name
     * @param string|null $code Identification code in the client system
     * @param string|null $status The item statis
     * @param string|null $description The item description
     * @param string|null $createdSince Filter for item's creation date start range
     * @param string|null $createdUntil Filter for item's creation date end range
     *
     * @return ListSubscriptionItemsResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getSubscriptionItems(
        string $subscriptionId,
        ?int $page = null,
        ?int $size = null,
        ?string $name = null,
        ?string $code = null,
        ?string $status = null,
        ?string $description = null,
        ?string $createdSince = null,
        ?string $createdUntil = null
    ): ListSubscriptionItemsResponse {
        return MockDataProvider::listSubscriptionItems([
            MockDataProvider::subscriptionItem($name),
        ], 1);
    }

    /**
     * Gets all subscriptions
     *
     * @param int|null $page Page number
     * @param int|null $size Page size
     * @param string|null $code Filter for subscription's code
     * @param string|null $billingType Filter for subscription's billing type
     * @param string|null $customerId Filter for subscription's customer id
     * @param string|null $planId Filter for subscription's plan id
     * @param string|null $cardId Filter for subscription's card id
     * @param string|null $status Filter for subscription's status
     * @param \DateTime|null $nextBillingSince Filter for subscription's next billing date start
     *        range
     * @param \DateTime|null $nextBillingUntil Filter for subscription's next billing date end range
     * @param \DateTime|null $createdSince Filter for subscription's creation date start range
     * @param \DateTime|null $createdUntil Filter for subscriptions creation date end range
     *
     * @return ListSubscriptionsResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getSubscriptions(
        ?int $page = null,
        ?int $size = null,
        ?string $code = null,
        ?string $billingType = null,
        ?string $customerId = null,
        ?string $planId = null,
        ?string $cardId = null,
        ?string $status = null,
        ?\DateTime $nextBillingSince = null,
        ?\DateTime $nextBillingUntil = null,
        ?\DateTime $createdSince = null,
        ?\DateTime $createdUntil = null
    ): ListSubscriptionsResponse {
        $sub1 = MockDataProvider::subscription();
        $sub2 = MockDataProvider::subscription();
        $sub3 = MockDataProvider::subscription();

        return MockDataProvider::listSubscriptions([$sub1, $sub2, $sub3], 3);
    }

    /**
     * Creates a increment
     *
     * @param string $subscriptionId Subscription id
     * @param CreateIncrementRequest $request Request for creating a increment
     * @param string|null $idempotencyKey
     *
     * @return GetIncrementResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createIncrement(
        string $subscriptionId,
        CreateIncrementRequest $request,
        ?string $idempotencyKey = null
    ): GetIncrementResponse {
        $increment = new GetIncrementResponse();
        $increment->setId(MockIdGenerator::generate('incr'));
        $increment->setValue(10.0);
        $increment->setIncrementType('percentage');
        $increment->setStatus('active');
        $increment->setCreatedAt(new \DateTime());
        $increment->setDescription('Mock increment');
        return $increment;
    }

    /**
     * Creates a usage
     *
     * @param string $subscriptionId Subscription Id
     * @param string $itemId Item id
     * @param CreateUsageRequest $body Request for creating a usage
     * @param string|null $idempotencyKey
     *
     * @return GetUsageResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createUsage(
        string $subscriptionId,
        string $itemId,
        CreateUsageRequest $body,
        ?string $idempotencyKey = null
    ): GetUsageResponse {
        $usage = new GetUsageResponse();
        $usage->setId(MockIdGenerator::generate('usage'));
        $usage->setQuantity(1);
        $usage->setDescription('Mock usage');
        $usage->setUsedAt(new \DateTime());
        $usage->setCreatedAt(new \DateTime());
        $usage->setStatus('active');
        $usage->setCode('mock_usage_code');
        $usage->setAmount(100);
        return $usage;
    }

    /**
     * @param string $subscriptionId The subscription id
     * @param string $discountId
     *
     * @return GetDiscountResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getDiscountById(string $subscriptionId, string $discountId): GetDiscountResponse
    {
        $discount = new GetDiscountResponse();
        $discount->setId($discountId);
        $discount->setStatus('active');
        $discount->setValue(10.0);
        $discount->setDiscountType('percentage');
        $discount->setCreatedAt(new \DateTime());
        $discount->setDescription('Mock discount');
        return $discount;
    }

    /**
     * Updates the metadata from a subscription
     *
     * @param string $subscriptionId The subscription id
     * @param UpdateMetadataRequest $request Request for updating the subscrption metadata
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSubscriptionMetadata(
        string $subscriptionId,
        UpdateMetadataRequest $request,
        ?string $idempotencyKey = null
    ): GetSubscriptionResponse {
        $sub = MockDataProvider::subscription();
        $sub->setId($subscriptionId);
        return $sub;
    }

    /**
     * @param string $subscriptionId Subscription Id
     * @param string $page Page number
     * @param string $size Page size
     *
     * @return ListCyclesResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getSubscriptionCycles(string $subscriptionId, string $page, string $size): ListCyclesResponse
    {
        return MockDataProvider::listCycles([MockDataProvider::period(1)], 1);
    }

    /**
     * Deletes a subscription item
     *
     * @param string $subscriptionId Subscription id
     * @param string $subscriptionItemId Subscription item id
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionItemResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function deleteSubscriptionItem(
        string $subscriptionId,
        string $subscriptionItemId,
        ?string $idempotencyKey = null
    ): GetSubscriptionItemResponse {
        $item = MockDataProvider::subscriptionItem();
        $item->setId($subscriptionItemId);
        $item->setStatus('deleted');
        return $item;
    }

    /**
     * @param string $subscriptionId The subscription id
     * @param int|null $page Page number
     * @param int|null $size Page size
     *
     * @return ListIncrementsResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getIncrements(string $subscriptionId, ?int $page = null, ?int $size = null): ListIncrementsResponse
    {
        $increment = new GetIncrementResponse();
        $increment->setId(MockIdGenerator::generate('incr'));
        $increment->setValue(10.0);
        $increment->setIncrementType('percentage');
        $increment->setStatus('active');
        $increment->setCreatedAt(new \DateTime());
        $increment->setDescription('Mock increment');

        $list = new ListIncrementsResponse();
        $list->setData([$increment]);
        $list->setPaging(MockDataProvider::paging(1));
        return $list;
    }

    /**
     * Updates a subscription item
     *
     * @param string $subscriptionId Subscription Id
     * @param string $itemId Item id
     * @param UpdateSubscriptionItemRequest $body Request for updating a subscription item
     * @param string|null $idempotencyKey
     *
     * @return GetSubscriptionItemResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function updateSubscriptionItem(
        string $subscriptionId,
        string $itemId,
        UpdateSubscriptionItemRequest $body,
        ?string $idempotencyKey = null
    ): GetSubscriptionItemResponse {
        $item = MockDataProvider::subscriptionItem();
        $item->setId($itemId);
        return $item;
    }
}
