<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Models\CreateTokenRequest;
use PagarmeApiSDKLib\Models\GetTokenResponse;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class TokensController extends BaseController
{
    /**
     * Gets a token from its id
     *
     * @param string $id Token id
     * @param string $publicKey Public key
     *
     * @return GetTokenResponse Response from the API call
     */
    public function getToken(string $id, string $publicKey): GetTokenResponse
    {
        $response = new GetTokenResponse();
        $response->setId($id);
        $response->setType('card');
        $response->setCreatedAt(new \DateTime());
        $response->setExpiresAt((new \DateTime('+1 hour'))->format('c'));
        return $response;
    }

    /**
     * @param string $publicKey Public key
     * @param CreateTokenRequest $request Request for creating a token
     * @param string|null $idempotencyKey
     *
     * @return GetTokenResponse Response from the API call
     */
    public function createToken(
        string $publicKey,
        CreateTokenRequest $request,
        ?string $idempotencyKey = null
    ): GetTokenResponse {
        $response = new GetTokenResponse();
        $response->setId(MockIdGenerator::generate('tok'));
        $response->setType('card');
        $response->setCreatedAt(new \DateTime());
        $response->setExpiresAt((new \DateTime('+1 hour'))->format('c'));
        return $response;
    }
}
