<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Models\CreateTransfer;
use PagarmeApiSDKLib\Models\GetTransfer;
use PagarmeApiSDKLib\Models\GetTransferSourceResponse;
use PagarmeApiSDKLib\Models\GetTransferTargetResponse;
use PagarmeApiSDKLib\Models\ListTransfers;
use PagarmeApiSDKLib\Mock\MockIdGenerator;
use PagarmeApiSDKLib\Mock\MockDataProvider;

class TransfersController extends BaseController
{
    /**
     * @param string $transferId
     *
     * @return GetTransfer Response from the API call
     */
    public function getTransferById(string $transferId): GetTransfer
    {
        return $this->buildMockTransfer($transferId);
    }

    /**
     * Gets all transfers
     *
     * @return ListTransfers Response from the API call
     */
    public function getTransfers(): ListTransfers
    {
        $transfer = $this->buildMockTransfer(MockIdGenerator::generate('tr'));
        $paging = MockDataProvider::paging(1);
        return new ListTransfers([$transfer], $paging);
    }

    /**
     * @param CreateTransfer $request
     *
     * @return GetTransfer Response from the API call
     */
    public function createTransfer(CreateTransfer $request): GetTransfer
    {
        return $this->buildMockTransfer(MockIdGenerator::generate('tr'));
    }

    private function buildMockTransfer(string $id): GetTransfer
    {
        $now = new \DateTime();

        $source = new GetTransferSourceResponse();
        $source->setSourceId(MockIdGenerator::generate('rp'));
        $source->setType('recipient');

        $target = new GetTransferTargetResponse();
        $target->setTargetId(MockIdGenerator::generate('rp'));
        $target->setType('recipient');

        return new GetTransfer(
            $id,
            MockIdGenerator::gatewayId(),
            10000,
            'transferred',
            $now,
            $now,
            'transfer',
            $source,
            $target
        );
    }
}
