<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Controllers;

use PagarmeApiSDKLib\Models\GetTransactionResponse;
use PagarmeApiSDKLib\Mock\MockIdGenerator;

class TransactionsController extends BaseController
{
    /**
     * @param string $transactionId
     *
     * @return GetTransactionResponse Response from the API call
     */
    public function getTransaction(string $transactionId): GetTransactionResponse
    {
        $response = new GetTransactionResponse();
        $response->setId($transactionId);
        $response->setGatewayId(MockIdGenerator::gatewayId());
        $response->setAmount(10000);
        $response->setStatus('paid');
        $response->setSuccess(true);
        $response->setCreatedAt(new \DateTime());
        $response->setUpdatedAt(new \DateTime());
        $response->setAttemptCount(1);
        $response->setMaxAttempts(3);
        $response->setTransactionType('transaction');
        return $response;
    }
}
